DROP TABLE IF EXISTS entry;

CREATE TABLE entry (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date DATE NOT NULL DEFAULT NOW(),
    content TEXT NOT NULL,
    monthid INTEGER NOT NULL
);

INSERT INTO entry (title, content, monthid)
values ('new entry', 'new entry content', 1);
